### PR TITLE
Fix Pr #357

### PR DESCRIPTION
**Pull request by erogluorhan**
This PR is put together to fix the following issues in PR #357:

- Numba errors (thanks to @rajeeja)
- Merge leftovers in documentation

### CODE REVIEW

**Comment by hongyuchen1030** [comment]
Thank you very much for the help! @erogluorhan @rajeeja

**Comment by rajeeja** [comment]
@hongyuchen1030 yes, changing to float64 will cause issues as that'd need way more changes and typecasting in all our readers. According to some numba documentation it's better to adhere to 'list' constructs.

**Comment by hongyuchen1030** [comment]
> @hongyuchen1030 yes, changing to float64 will cause issues as that'd need way more changes and typecasting in all our readers. According to some numba documentation it's better to adhere to 'list' constructs.

Thank you very much for your explanation. So `numba` recommends using `list` than `numpy`?

**Comment by rajeeja** [comment]
> > @hongyuchen1030 yes, changing to float64 will cause issues as that'd need way more changes and typecasting in all our readers. According to some numba documentation it's better to adhere to 'list' constructs.
> 
> Thank you very much for your explanation. So `numba` recommends using `list` than `numpy`?

No, the problem is Numba is just type sensitive, we must have functions use either one or make different versions for each type (one for float and one for list) if we use float, we must make sure that all calls are made with floats and not lists and vice-versa. Since, we are reading different files and not typecasting the values read, we go with lists - so the statement - "numba recommends using list than numpy?" is False. It is as per our use case.

**Comment by hongyuchen1030** [comment]
> typecasting

I am still confused here: We are changing between the `list` and `numpy.array` now.

So previously: The function takes `python float list` as input and output `python float list`

And I want to change it to: The function takes `python float list` or `numpy.array of float` as input and output `numpy.array of float`

We are always dealing with `float` here, just either in `numpy.array` or `python list`

**Comment by hongyuchen1030** [comment]
> > > @hongyuchen1030 yes, changing to float64 will cause issues as that'd need way more changes and typecasting in all our readers. According to some numba documentation it's better to adhere to 'list' constructs.
> > 
> > 
> > Thank you very much for your explanation. So `numba` recommends using `list` than `numpy`?
> 
> No, the problem is Numba is just type sensitive, we must have functions use either one or make different versions for each type (one for float and one for list) if we use float, we must make sure that all calls are made with floats and not lists and vice-versa. Since, we are reading different files and not typecasting the values read, we go with lists - so the statement - "numba recommends using list than numpy?" is False. It is as per our use case.

I am still confused here: We are changing between the `list` and `numpy.array` now.

So previously: The function takes `python float list` as input and output `python float list`

And I want to change it to: The function takes `python float list` or `numpy.array` of `float` as input and output `numpy.array` of `float`

We are always dealing with `float` here, just either in `numpy.array` or `python list`

**Comment by rajeeja** [comment]
agreed and

> > > > @hongyuchen1030 yes, changing to float64 will cause issues as that'd need way more changes and typecasting in all our readers. According to some numba documentation it's better to adhere to 'list' constructs.
> > > 
> > > 
> > > Thank you very much for your explanation. So `numba` recommends using `list` than `numpy`?
> > 
> > 
> > No, the problem is Numba is just type sensitive, we must have functions use either one or make different versions for each type (one for float and one for list) if we use float, we must make sure that all calls are made with floats and not lists and vice-versa. Since, we are reading different files and not typecasting the values read, we go with lists - so the statement - "numba recommends using list than numpy?" is False. It is as per our use case.
> 
> I am still confused here: We are changing between the `list` and `numpy.array` now.
> 

Datatype of the function is important and should be the same for all callers and callee. We can change to float, but that'd need much bigger change. It might be the right thing to do, but not in the scope of this PR. My recommendation is to use the old signatures for the functions now.  We would have to change all other caller/callee for the function if we want the code to not fail.  Small managable PRs :)

**Comment by hongyuchen1030** [comment]
> agreed and
> 
> > > > > @hongyuchen1030 yes, changing to float64 will cause issues as that'd need way more changes and typecasting in all our readers. According to some numba documentation it's better to adhere to 'list' constructs.
> > > > 
> > > > 
> > > > Thank you very much for your explanation. So `numba` recommends using `list` than `numpy`?
> > > 
> > > 
> > > No, the problem is Numba is just type sensitive, we must have functions use either one or make different versions for each type (one for float and one for list) if we use float, we must make sure that all calls are made with floats and not lists and vice-versa. Since, we are reading different files and not typecasting the values read, we go with lists - so the statement - "numba recommends using list than numpy?" is False. It is as per our use case.
> > 
> > 
> > I am still confused here: We are changing between the `list` and `numpy.array` now.
> 
> Datatype of the function is important and should be the same for all callers and callee. We can change to float, but that'd need much bigger change. It might be the right thing to do, but not in the scope of this PR. My recommendation is to use the old signatures for the functions now. We would have to change all other caller/callee for the function if we want the code to not fail. Small managable PRs :)

I understand with your concerns and agree with that. I am just confuse what does the `float` means here? We are always using `float`, right? Just either with the `numpy.array` or `python list`.

I guess what you mean for `float` is `numpy.array`?

**Comment by rajeeja** [comment]
> > agreed and
> > > > > > @hongyuchen1030 yes, changing to float64 will cause issues as that'd need way more changes and typecasting in all our readers. According to some numba documentation it's better to adhere to 'list' constructs.
> > > > > 
> > > > > 
> > > > > Thank you very much for your explanation. So `numba` recommends using `list` than `numpy`?
> > > > 
> > > > 
> > > > No, the problem is Numba is just type sensitive, we must have functions use either one or make different versions for each type (one for float and one for list) if we use float, we must make sure that all calls are made with floats and not lists and vice-versa. Since, we are reading different files and not typecasting the values read, we go with lists - so the statement - "numba recommends using list than numpy?" is False. It is as per our use case.
> > > 
> > > 
> > > I am still confused here: We are changing between the `list` and `numpy.array` now.
> > 
> > 
> > Datatype of the function is important and should be the same for all callers and callee. We can change to float, but that'd need much bigger change. It might be the right thing to do, but not in the scope of this PR. My recommendation is to use the old signatures for the functions now. We would have to change all other caller/callee for the function if we want the code to not fail. Small managable PRs :)
> 
> I understand with your concerns and agree with that. I am just confuse what does the `float` means here? We are always using `float`, right? Just either with the `numpy.array` or `python list`.
> 
> I guess what you mean for `float` is `numpy.array`?

yes, I can revisit all Numba decorated functions and analyze which one is better after this PR is done.

**Pull request merged**
